Voice_Blogs/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import BlogDetailView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('django.contrib.auth.urls')),
    path("", include('main.urls')),
    path("", include('user.urls')),
    path("blog/<int:pk>",BlogDetailView.as_view(), name='blog-detail'),
    # path("myBlogs/<int:pk>",MyBlogs.as_view(), name='myBlogs'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views


app_name = 'main'

urlpatterns = [
    path('',views.HomePage.as_view(), name='home'),
    # path('login',views.LoginPage.as_view(), name='login'),
    path('register',views.register_user, name='register'),
    path('about',views.about_page, name='about'),
    path('<str:user>/create-profile',views.profile_save, name='profile')
]

user/urls.py
from django.urls import path
from main.views import HomePage
from user.views import my_blogs, CreateBlogView, UpdateBlogView, blog_publish, DraftListView, DeleteBlogView, add_a_comment, delete_comment,CategoryView, like_blog, profile_page, UpdateProfileView

app_name = 'user'
urlpatterns = [
    path("",HomePage.as_view(), name='home'),
    path("<str:user>/myBlogs",my_blogs, name='myBlogs'),
    # path("myBlogs",MyBlogs.as_view(), name='myBlogs'),
    path("<str:user>/myDrafts", DraftListView.as_view(), name='myDrafts'),
    path("<str:user>/myProfile", profile_page, name='myProfile'),
    path("<str:user>/createBlog",CreateBlogView.as_view(), name='createBlog'),
    path("edit/<int:pk>",UpdateBlogView.as_view(), name='editBlog'),
    path("profile/edit/<int:pk>",UpdateProfileView.as_view(), name='editProfile'),
    path("publish/<int:pk>", blog_publish, name='publishBlog'),
    path("like/<int:pk>", like_blog, name='likeBlog'),
    path("<str:user>/delete/<int:pk>", DeleteBlogView.as_view() , name='deleteBlog'),
    path("deleteComment/<int:pk>", delete_comment , name='deleteComment'),
    path("<str:uname>/comment/<int:pk>", add_a_comment, name='comment'),
    path("category/<str:category>", CategoryView, name='category'),
    path("<str:user>/<str:page>/<str:category>", CategoryView, name='category'),

]

main/forms.py
from django import forms
# from main.models import Blog
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from user.models import UserProfile



class CustomUserCreationForm(UserCreationForm):

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form form-control'}),label="Password",max_length=30)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form form-control'}),label="Confirm Password",max_length=30)


    class Meta:
        model = User
        fields = ('username',)

        help_texts = {
            'username': "",
        }

    def __init__(self, *args,**kwargs):
        super(CustomUserCreationForm,self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form form-control'
            

class UserProfileForm(forms.ModelForm):


    class Meta:
        model = UserProfile
        fields = ('email','profile_pic','first_name','last_name','description')

        widgets = {
            'email': forms.TextInput(attrs={
            'class': 'form form-control',
            }),
            'first_name': forms.TextInput(attrs={
            'class': 'form form-control',
            }),
            'last_name': forms.TextInput(attrs={
            'class': 'form form-control',
            }),
            'profile_pic': forms.FileInput(attrs={
            'class': 'form form-control',
            }),
            'description': forms.Textarea(attrs={
            'class': 'form form-control',
            }),
        }

        

main/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect, HttpResponseNotFound

from main.forms import CustomUserCreationForm,UserProfileForm
from django.urls import reverse_lazy, reverse
from user.models import Blog,Category,UserProfile

# Create your views here.

class HomePage(generic.ListView):
    
    model = Blog
    context_object_name = 'blogs'
    template_name = 'main/home.html'

    def get_context_data(self,*args, **kwargs):
        contex =  super(HomePage,self).get_context_data(*args,**kwargs)
        contex['cat_list'] = Category.objects.all()
        
        return contex

    def get_queryset(self, *args,**kwargs):
        
        return Blog.objects.all().filter(publish_date__isnull=False).order_by('-publish_date')


def register_user(request):

    form = CustomUserCreationForm()
    if request.method == "POST":
        # print("Check point 1")
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            user = form.save()
            user.save()
            return HttpResponseRedirect(reverse('main:profile',kwargs={'user':username}))

    
    return render(request,'registration/register.html',{'form':form})

class ProfileView(generic.CreateView):
    model = UserProfile
    template_name = 'user/profileEdit.html'
    # fields = ('title','content')
    form_class = UserProfileForm
    success_url = reverse_lazy('login')

    def form_valid(self,form):
        user = User.objects.filter(username = self.kwargs['user'])[0]
        form.instance.user = user
        return super().form_valid(form)
    
def profile_save(request,user):

    if request.method == "POST":
        form = UserProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            user_is = User.objects.filter(username=user)[0]
            profile.user = user_is

            if 'profile_pic' in request.FILES:
                # print('Found It!')
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            return HttpResponseRedirect(reverse('login'))
        
    user = User.objects.filter(username=user)[0]
    # print(user)
    # print(profile)
    if UserProfile.objects.filter(user=user).count() == 0:
        form = UserProfileForm()
        return render(request,'user/profileCreate.html', {'form':form,'user':user})
    else:
        return HttpResponseNotFound("No Such Page!!")


def about_page(request):
    return render(request, 'main/about.html')

templates/main/about.html
<!DOCTYPE html>
{% extends 'main/base.html' %}
{% block body_block %}
    <div class="container text-center">
        <H1>Welcome to Voice Blog</H1>
        <h3>This website is created by</h3>
        <h4>Himanshu mamgain</h4>
        <h5>Email: mamgainjii@gmail.com</h5>
        <p>Plzz mail us if you found any bugs | Suggestion are always welcomed 😁😁 </p>
        
        <hr>
    </div>
    <div class="container text-left">

        <h4 class="text-center">*****Acknowledgement****</h4>
        <h5></h5>This website took inspiration from folllowing projects: </h6>
        <ol>
            <li>Blog Project from Python-Django full stack web developments By Jose Portilla available on udemy</li>
            <li>Blog Project from codemy.com available on youtube</li>

        </ol>
    </div>
{% endblock %}

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title_block %}
      VOICE BLOGS
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    
    <!-- Medium Text Link
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8"> -->
    
    <link rel="stylesheet" href="/static/css/base.css">
    {% block link_block%}
    {%endblock%}
</head>
<body>
  <div class="container text-center" id="voice">
    <h1>VOICE BLOGS</h1>
    <h6>Explore Experiment Express</h6>
    <!-- <a class="nav-link" href="/admin">Admin</a> -->
  </div>
  <nav class="navbar  sticky-top" style="background-color: #e3f2fd;" id="testing">
    <div class="container-fluid" >
      <div>
        <a class="navbar-brand" href="{% url 'main:home' %}">VOICE</a>
      </div>
      {% if user.is_authenticated %}
      <div id="user_name">
        <h2 class="text-center" >{{user.username}}</h2>
      </div>
      {% endif %}
      
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel" style="background-color: #e3f2fd;">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">
          Hii, {{user.first_name}} {{user.last_name}}
          </h5>
          <button type="button" class="btn-close btn-close-black" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'main:home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'user:createBlog' user.username %}" class="nav-link" aria-current="page">Create Blog</a>

            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'user:myProfile' user.username %}">My Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'user:myBlogs' user.username %}">My Blogs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'user:myDrafts' user.username %}">My Drafts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'logout' %}"><b>Logout</b>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                  <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                </svg>
              </a>
            </li>
            
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:about' %}">About</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}"><b>Login</b></a>
            </li>
            {% endif %}
            
          </ul>
        </div>
      </div>
    </div>
  </nav>
  
    {% block body_block%}
    {% endblock%}
    


    <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    
</body>
</html>

templates/main/category_list.html
<div class="dropdown text-center"style="margin: 20px;">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      {%if category%}
      {{category|title}}
      {% else %}
      ALL BLOGS
      {%endif%}
    </button>
    <ul class="dropdown-menu">
      {%if page == "myBlogs" %}
        <li><a class="dropdown-item" href="{% url 'user:myBlogs' user.username %}">ALL BLOGS</a></li>
      {%elif page == "myDrafts" %}
        <li><a class="dropdown-item" href="{% url 'user:myDrafts' user.username %}">ALL BLOGS</a></li>
      {% else %}
        <li><a class="dropdown-item" href="{% url 'main:home' %}">ALL BLOGS</a></li>
      {% endif %}
      {% for cat in cat_list %}
        {% if page %}
        <li><a class="dropdown-item" href="{% url 'user:category' category=cat.name|slugify user=user.username page=page %}">{{ cat.name }}</a></li>
        {%else%}
        <li><a class="dropdown-item" href="{% url 'user:category' cat.name|slugify %}">{{ cat.name }}</a></li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>

templates/main/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Sorry! This page doesnot exist</h1>
</body>
</html>

templates/main/home.html
<!DOCTYPE html>
{% extends 'main/base.html'%}
{% load my_filters %}
{% block body_block %}
{% include 'main/category_list.html' %}
    <div class="blogs">
        {% for blog in blogs %}
        <div class="blog container-fluid">
            <a href="{% url 'blog-detail' blog.pk %}">
            <h6 class="text-center">{{blog.publish_date|date:"d/m/y"}}</h6>
            <hr>
                <h4>{{blog.title}}</h4>
                <h6>By: {{blog.author.username}}</h6>
                <p>{{ blog.snippet }}</p>
                <hr>
                <div class="lV">
                    <h5>
                        Likes: {{ blog|test }}
                    </h5>
                    <h5>
                        Views: {{ blog|views_count }}
                    </h5>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
{% endblock %}