Voice_Blogs/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import BlogDetailView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('django.contrib.auth.urls')),
    path("", include('main.urls')),
    path("", include('user.urls')),
    path("blog/<int:pk>",BlogDetailView.as_view(), name='blog-detail'),
    # path("myBlogs/<int:pk>",MyBlogs.as_view(), name='myBlogs'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views


app_name = 'main'

urlpatterns = [
    path('',views.HomePage.as_view(), name='home'),
    # path('login',views.LoginPage.as_view(), name='login'),
    path('register',views.register_user, name='register'),
    path('about',views.about_page, name='about'),
    path('<str:user>/create-profile',views.profile_save, name='profile')
]

user/urls.py
from django.urls import path
from main.views import HomePage
from user.views import my_blogs, CreateBlogView, UpdateBlogView, blog_publish, DraftListView, DeleteBlogView, add_a_comment, delete_comment,CategoryView, like_blog, profile_page, UpdateProfileView

app_name = 'user'
urlpatterns = [
    path("",HomePage.as_view(), name='home'),
    path("<str:user>/myBlogs",my_blogs, name='myBlogs'),
    # path("myBlogs",MyBlogs.as_view(), name='myBlogs'),
    path("<str:user>/myDrafts", DraftListView.as_view(), name='myDrafts'),
    path("<str:user>/myProfile", profile_page, name='myProfile'),
    path("<str:user>/createBlog",CreateBlogView.as_view(), name='createBlog'),
    path("edit/<int:pk>",UpdateBlogView.as_view(), name='editBlog'),
    path("profile/edit/<int:pk>",UpdateProfileView.as_view(), name='editProfile'),
    path("publish/<int:pk>", blog_publish, name='publishBlog'),
    path("like/<int:pk>", like_blog, name='likeBlog'),
    path("<str:user>/delete/<int:pk>", DeleteBlogView.as_view() , name='deleteBlog'),
    path("deleteComment/<int:pk>", delete_comment , name='deleteComment'),
    path("<str:uname>/comment/<int:pk>", add_a_comment, name='comment'),
    path("category/<str:category>", CategoryView, name='category'),
    path("<str:user>/<str:page>/<str:category>", CategoryView, name='category'),

]

user/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse('user:home')


class Blog(models.Model):
    title = models.CharField(max_length=50)
    content = RichTextField(blank=True, null=True)
    title_tag = models.CharField(max_length=50)
    publish_date = models.DateTimeField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=40)
    likes = models.ManyToManyField(User, related_name="blog_likes")
    views = models.ManyToManyField(User, related_name="blog_views")
    snippet = models.TextField(max_length=100)

    class Meta:
        ordering = ['-publish_date']

    def total_likes(self):
        return self.likes.count()
    
    def total_views(self):
        return self.views.count()

    def publish(self):
        self.publish_date = timezone.now()

    def __str__(self):
        return f'{self.title} By {self.author.username}'
    
    def get_absolute_url(self):
        return reverse('blog-detail', kwargs={'pk':self.pk})
    
# class Comment(models.Model):
#     author = models.ForeignKey(User, on_delete=models.CASCADE)
#     content = models.TextField()

class Comment(models.Model):
    blog = models.ForeignKey(Blog, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time =  models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-time']


    def __str__(self):
        return f'{self.author.username} on {self.blog.title}'

    def get_absolute_url(self):
        return reverse('blog-detail', kwargs={'pk':self.blog_id})
    

class UserProfile(models.Model):

    user = models.OneToOneField(User, related_name="profile",on_delete=models.CASCADE)

    # Adding additional feilds

    profile_pic = models.ImageField(blank=True,null=True,upload_to='images/profile')
    email = models.EmailField()
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    description = models.TextField(max_length=250, blank=True)
     

    def __str__(self):
        return f'USER NAME: {self.user.username}'
    
    def get_absolute_url(self):
        return reverse('user:myProfile',kwargs={'user':self.user.username})

user/forms.py
from django import forms
from user.models import Comment,Blog, Category

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

        labels = {
            'text': '',
        }

        widgets ={
            'text': forms.Textarea(attrs= {
            'class': 'form form-control',
            'placeholder': 'Enter Your comment',
            'rows': 2,
            'style': 'resize:none;'
            })
        }



input_style = 'background-color: aliceblue; border: 1px solid black;'

category = Category.objects.all().values_list('name','name')
category_list = []

for item in category:
    category_list.append(item)

class CreateBlogForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = ('title','title_tag', 'category', 'snippet','content')

        labels = {
            'title': '',
            'title_tag': '',
            'category': '',
            'content': 'Content',
            'snippet': '',
        }

        widgets = {
            "title": forms.TextInput(attrs={
            'placeholder': "Enter Blog Title",
            'class': "form form-control text-center",
            'style': input_style,
            }),
            "title_tag": forms.TextInput(attrs={
            'placeholder': "Enter Blog Tag",
            'class': "form form-control text-center",
            'style': input_style,
            }),
            "category": forms.Select(choices= category_list,attrs={
            'class': "form form-select text-center",
            'style': input_style,
            }),
            "content": forms.Textarea(attrs={
            'style': f"resize:none;{input_style}",
            'class': "editable medium-editor-textarea form form-control",
            }),
            "snippet": forms.Textarea(attrs={
            'style': f"resize:none;{input_style}",
            'rows':4,
            'cols':6,
            'placeholder': "Enter your article snippet",
            'class': "form form-control text-center",
            })
        }

user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy,reverse
from django.views import generic
from user.models import Blog, Comment, Category, UserProfile
from user.forms import CommentForm,CreateBlogForm
from main.forms import UserProfileForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect
from django.contrib.auth.models import User


# # Create your views here.
# class MyBlogs(generic.ListView):
#     model = Blog
#     template_name = "user/myBlogs.html"
#     context_object_name = 'blogs'

#     def get_queryset(self, *args,**kwargs):
#         return Blog.objects.filter(author_id = self.kwargs.get('pk'))
    
@login_required
def my_blogs(request,user):

    # print(user)
    author = User.objects.filter(username=user)[0].pk
    # print(author)
    blogs = Blog.objects.all().filter(author=author, publish_date__isnull=False)
    return render(request, 'user/myBlogs.html', {'blogs':blogs,'page':'myBlogs','cat_list': Category.objects.all()})

class BlogDetailView(LoginRequiredMixin, generic.DetailView):
    login_url = '/login/'
    model = Blog
    context_object_name = 'blog'
    template_name = 'user/blogDetail.html'

    def get_context_data(self, *args,**kwargs):
        contex =  super(BlogDetailView, self).get_context_data(*args,**kwargs)
        blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        liked = False
        if blog.likes.filter(pk=self.request.user.id).exists():
            liked = True
        if not blog.views.filter(pk=self.request.user.id).exists():
            blog.views.add(self.request.user)

        likes_count = blog.total_likes()
        contex['likes'] = likes_count
        contex['liked'] = liked

        return contex
    


class CreateBlogView(LoginRequiredMixin, generic.CreateView):
    login_url = '/login/'
    redirect_field_name = 'user/blogDetail.html'
    model = Blog
    template_name = 'user/createBlog.html'
    # fields = ('title','content')
    form_class = CreateBlogForm

    def form_valid(self,form):
        author_id = User.objects.filter(username = self.kwargs['user'])[0].pk
        form.instance.author_id = author_id
        return super().form_valid(form)

class UpdateBlogView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    redirect_field_name = 'user/blogDetail.html'
    model = Blog
    template_name = 'user/updateBlog.html'
    # fields = ('title','content')
    form_class = CreateBlogForm

class DraftListView(LoginRequiredMixin,generic.ListView):
    login_url = '/login/'
    # redirect_field_name = 'user/home.html'
    template_name = 'user/myBlogs.html'

    model = Blog
    context_object_name = 'blogs'

    def get_context_data(self,*args, **kwargs):
        contex =  super(DraftListView,self).get_context_data(*args,**kwargs)
        contex['cat_list'] = Category.objects.all()
        contex['page'] = "myDrafts"
        
        return contex

    def get_queryset(self):
        author = User.objects.filter(username = self.kwargs['user'])[0].pk
        # print(author)
        return Blog.objects.all().filter(author=author, publish_date__isnull=True)

class DeleteBlogView(LoginRequiredMixin,generic.DeleteView):
    model = Blog
    template_name = 'user/deleteBlog.html'
    def get_success_url(self):
        return reverse_lazy('user:myBlogs',kwargs={'user':self.kwargs['user']})
    context_object_name = 'blog'

@login_required
def blog_publish(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    blog.publish()
    blog.save()
    return redirect('user:home')

@login_required
def add_a_comment(request, pk,uname):
    # print(pk)
    # print(uname)
    form = CommentForm
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():

            author = User.objects.get(username = uname)
            blog = Blog.objects.get(pk = pk)
            sv = form.save(commit=False)
            sv.blog = blog
            sv.author = author
            sv.save()
            return HttpResponseRedirect(reverse('blog-detail', kwargs={'pk':pk}))
    return render(request, 'user/comment.html', {'form':form})

@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    blog_pk = comment.blog.pk
    comment.delete()
    return HttpResponseRedirect(reverse('blog-detail',kwargs={'pk':blog_pk}))


def CategoryView(request, category,user="",page=""):

    cat_list = Category.objects.all()
    if user != "":
        user_id = User.objects.filter(username = user)[0].pk
        data = []
        if page == "myBlogs":
            data = Blog.objects.filter(author=user_id,publish_date__isnull=False,category=category.title().replace("-"," "))
        else:
            data = Blog.objects.filter(author=user_id,publish_date__isnull=True,category=category.title().replace("-"," "))
        
        return render(request, 'user/category.html', {'category': category,'blogs':data,'cat_list':cat_list,'page':page})


    data = Blog.objects.filter(category=category.title().replace("-"," "))
    

    return render(request, 'user/category.html', {'category': category,'blogs':data,'cat_list':cat_list})

@login_required
def like_blog(request,pk):
    blog = get_object_or_404(Blog, id=pk)
    if blog.likes.filter(pk = request.user.id).exists():
        blog.likes.remove(request.user)
    else:
        blog.likes.add(request.user)

    return HttpResponseRedirect(reverse('blog-detail',kwargs={'pk':pk}))

@login_required
def profile_page(request,user):

    return render(request, 'user/profile.html', {'check':user})


class UpdateProfileView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    redirect_field_name = 'user/profile.html'
    model = UserProfile
    template_name = 'user/profileEdit.html'
    # fields = ('title','content')
    form_class = UserProfileForm

    def get_context_data(self,*args, **kwargs):
        contex =  super(UpdateProfileView,self).get_context_data(*args,**kwargs)
        contex['pk'] = self.kwargs['pk']
        
        
        return contex

templates/user/blogDetail.html
<!DOCTYPE html>
{% extends 'main/base.html'%}
{% load static %}
{% block title_block %}
{{blog.title}}
{% endblock %}
{% block link_block %}
<link rel="stylesheet" href="/static/css/remove.css">
<link rel="stylesheet" href="/static/css/blog_detail.css">
{% endblock %}
{% block body_block %}
    
    <div class="container" id="blog-detail">
        <h2 class="text-center" style="font-size: 30px;">{{blog.title}}</h2>
        <h6 class="text-center">By: {{blog.author.username}}</h6>
        {% if blog.publish_date == null %}
        <div class="text-center">
            <a href="{% url 'user:publishBlog' blog.pk%}"><button class="btn btn-warning">Publish</button></a>
        </div>
        {% else %}
        <h6 class="text-center">{{blog.publish_date|date:"l, d F Y"}}</h6>
        {% endif %}
        <p class="text-center" style="color: red; ">{{ blog.title_tag }}</p>
        <!-- <p class="text-center"><strong>Category: {{blog.category}}</strong></p> -->
        <div class="text-center" id="updateLinks">
            
            {% if blog.author.username == user.username %}
            <a style="margin-right: 10px;" href="{% url 'user:deleteBlog' pk=blog.pk user=user.username %}">Delete</a>
            
            <a href="{% url 'user:editBlog' blog.pk %}">Edit</a>
            {% endif %}
        </div>
        <hr>
        <p>{{ blog.content|safe }}</p>
        <hr>
        <div class="funcBlog" >
            <form action="{% url 'user:likeBlog' blog.pk %}" method="post" style="display: flex; flex-direction: row;">
                {% csrf_token %}
                {% if liked %}
                <button class="btn btn-danger">Unlike</button>
                {% else %}
                <button class="btn btn-primary">Like</button>
                {% endif %}
                <h5 class="text-center" style="padding-top: 7px;">&ensp;{{ likes }} likes</h5>
            </form>
            <a href="{% url 'main:home' %}" class="btn btn-secondary">Home</a>
            
        </div>
        <hr>
        <div class="card">
            <div class="row">
              <div class="col-sm-2 text-center">
                {% if blog.author.profile.profile_pic%}
                    <img src="{{blog.author.profile.profile_pic.url}}" class="rounded-circle border border-primary" height="150" width="150" style="margin: 10px;">
                {% else %}
                    <img src="{% static 'images/default_profile.png' %}" class="rounded-circle border border-primary" height="150" width="150" style="margin: 10px;">
                {% endif %}
              </div>
              <div class="col-sm-10">
                <div class="card-body">
                  <h5 class="card-title">{{blog.author.profile.first_name}} {{blog.author.profile.last_name}}</h5>
                  <h6>{{blog.author.profile.email}}</h6>
                  <p>{{blog.author.profile.description}}</p>
                </div>
              </div>
            </div>
          </div>
        <hr>
        {% if blog.publish_date %}
            <h4>Comments....</h4>
            <a href="{% url 'user:comment' user.username blog.pk %}">Add Comment</a>
            
            <div class="container" id="comments">
                {% for comment in blog.comments.all %}
                    <h6>{{ comment.author}} - {{ comment.time }}&emsp;
                        {%if user.username == blog.author.username %}
                            <a href="{% url 'user:deleteComment' comment.pk %}">Delete</a>
                        {% endif %}
                    </h6>
                    <p style="padding-left: 20px;">{{ comment.text }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </div>

{% endblock %}

templates/user/category.html
<!DOCTYPE html>
{% extends 'main/base.html'%}
{% load my_filters %}
{% block body_block %}
    {% include 'main/category_list.html'%}
    {% if blogs %}
    <div class="blogs">

        {% for blog in blogs %}
        <div class="blog container-fluid">
            <a href="{% url 'blog-detail' blog.pk %}">
                <h6 class="text-center">{{blog.publish_date|date:"d/m/y"}}</h6>
                <hr>
                <h4>{{blog.title}}</h4>
                <h6>By: {{blog.author.username}}</h6>
                <p>{{ blog.snippet }}</p>
                <hr>
                <div class="lV">
                    <h5>
                        Likes: {{ blog|test }}
                    </h5>
                    <h5>
                        Views: {{ blog|views_count }}
                    </h5>
                </div>
                
            </a>
            
        </div>
        {% endfor %}
    </div>
    {%else%}
    <h1 class="text-center">Sorry!! No Blogs in this Category</h1>
    {% endif %}
{% endblock %}

templates/user/comment.html
<!DOCTYPE html>
{% extends 'main/base.html'%}
{% block body_block%}
    <div class="createBlog container">
        <h2 class="text-center">This is Comment page</h2>
        <form method="post" class="text-center">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                <button class="btn btn-success">
                    Comment
                </button>
                
            </div>
        </form>

    </div>
{% endblock %}

templates/user/createBlog.html
<!DOCTYPE html>
{% extends 'main/base.html'%}
{% block body_block%}
    <div class="createBlog container">
        <h2 class="text-center">Create Your Blog</h2>
        <form method="post"  id="createBlog">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <div class="text-center">
                <button class="btn btn-success">
                        Save
                </button>
                
            </div>
        </form>
        <a href="{% url 'user:myBlogs' user.username %}" class="btn btn-secondary" style="margin-bottom: 10px;">Back</a>

    </div>
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

templates/user/deleteBlog.html
{% extends "main/base.html" %}
{% block body_block %}
  {%if user.username == blog.author.username%}
  <form  method="post" class="deleteBlog container">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ blog }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
    <a href="{% url 'blog-detail' blog.pk %}" class="btn btn-warning">Cancel</a>
  </form>
  {% else %}
  <h1 class="text-center" style="margin-top: 20px;">Sorry!! NO Such page exist</h1>
  {% endif %}
{% endblock %}

templates/user/myBlogs.html
<!DOCTYPE html>
{% extends 'main/base.html'%}
{% load my_filters %}
{% block body_block %}
    {% include 'main/category_list.html'%}
    
    {% if blogs %}
        <div class="blogs container-fluid">
            
            {% for blog in blogs %}
            
            <div class="blog container-fluid">
                <a href="{% url 'blog-detail' blog.pk %}">
                    <h6 class="text-center">{{blog.publish_date|date:"d/m/y"}}</h6>
                    <hr>
                    <h4>{{blog.title}}</h4>
                    <h6>By: {{blog.author.username}}</h6>
                    <p>{{ blog.snippet }}</p>
                    <hr>
                    <div class="lV">
                        <h5>
                            Likes: {{ blog|test }}
                        </h5>
                        <h5>
                            Views: {{ blog|views_count }}
                        </h5>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <h2 class="text-center" style="margin-top: 20px;">No Blogs Here</h2>
    {% endif %}
{% endblock %}

templates/user/profile.html
<!DOCTYPE html>
{% extends 'main/base.html' %}
{% load static%}
{% block link_block %}
    <link rel="stylesheet" href="/static/css/remove.css">
    <link rel="stylesheet" href="/static/css/myProfile.css">
{% endblock %}
{% block body_block %}

{%if check == user.username %}
    
<div class="card container" style="margin-top:20px;" id="profile-box">
<div class="row">
  <div class="col-sm-4 text-center">
    {% if user.profile.profile_pic%}
        <img src="{{user.profile.profile_pic.url}}" class="rounded-circle border border-primary" style="margin: 10px;">
    {% else %}
        <img src="{% static 'images/default_profile.png' %}" class="rounded-circle border border-primary" style="margin: 10px;">
    {% endif %}
  </div>
  <div class="col-sm-8">
    <div class="card-body" style="display: grid;grid-template-rows: 5fr 1fr;">
        <div class="profile">
            <h4 class="card-title">{{user.profile.first_name}} {{user.profile.last_name}}</h4>
            <h5 class="card-title">{{user.username}}</h5>
            <h6>{{user.profile.email}}</h6>
            <p>{{user.profile.description}}</p>
        </div>
        <div class="edit">
            <a href="{% url 'user:editProfile' user.profile.pk %}" class="btn btn-danger">Edit</a>
        </div>
      
    </div>
  </div>
</div>
</div>
    <div class="container text-center" id="favouraite" style="margin-top: 10px;">
        <h2>My Favourite Blogs</h2>
        <h5>Feature Coming Soon</h5>
    </div>

{% else %}
<h1 class="text-center">Sorry! No such page exist</h1>
{% endif %}
{% endblock %}

templates/user/profileCreate.html
<!DOCTYPE html>
{% extends 'main/base.html'%}
{% block link_block%}
    <link rel="stylesheet" href="/static/css/register.css">
    <link rel="stylesheet" href="/static/css/create_profile.css">
{% endblock %}
{% block body_block %}
    
    <h2 class="text-center">
        Create Profile
    </h2>
        <form method="post" class="container" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                
                <button class="btn btn-success " type="submit">Save</button>
                
            </div>
            
        </form>
{% endblock %}

templates/user/profileEdit.html
<!DOCTYPE html>
{% extends 'main/base.html'%}
{% block link_block%}
    <link rel="stylesheet" href="/static/css/register.css">
{% endblock %}
{% block body_block %}
    {% if user.profile.pk == pk%}
    <h2 class="text-center">
        Update Profile
    </h2>
        <form method="post" class="container" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                
                <button class="btn btn-success " type="submit">Update</button>
                
            </div>
            
        </form>
    {% else %}
        <h2 class="text-center">Sorry!no such page exist.</h2>
    {% endif %}
{% endblock %}

templates/user/test.html
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rem velit unde, asperiores consectetur consequatur sapiente quas nostrum qui doloribus quia officiis alias eligendi hic, laudantium architecto dicta, voluptatum doloremque. Quasi, iusto provident nam cumque corrupti inventore voluptate, consequatur expedita tempora explicabo, aspernatur similique sint alias veritatis repudiandae tempore aperiam impedit. Itaque ipsam aliquid quae minus dolor, libero corrupti sed nemo. Sint laudantium modi voluptatem blanditiis asperiores dicta eos earum natus corrupti quod veniam ipsa est tenetur facilis minima, facere hic, officia saepe? Magni officiis odit ullam nulla laborum deleniti ducimus iste, nostrum dolor voluptatem odio, rem possimus maiores et explicabo quas aliquam! Cum quam ipsa, quisquam aliquid impedit rerum sapiente laudantium molestiae accusantium velit soluta, repellendus delectus nulla omnis aliquam reprehenderit dignissimos voluptatibus quod quo eligendi voluptatem ut saepe! Recusandae maxime quia incidunt exercitationem dolorem architecto, assumenda nesciunt, facilis, fugiat laudantium consequatur beatae illo saepe adipisci cupiditate nulla molestiae voluptatibus!

templates/user/updateBlog.html
<!DOCTYPE html>
{% extends 'main/base.html'%}
{% block body_block%}
    {%if user.username == blog.author.username%}
    <div class="createBlog container">
        <h2 class="text-center">Update Your Blog</h2>
        <form method="post"  id="createBlog">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <div class="text-center">
                <button class="btn btn-success">
                        Update
                </button>
                
            </div>
        </form>
        <a href="{% url 'user:myBlogs' user.username %}" class="btn btn-secondary" style="margin-bottom: 10px;">Back</a>

    </div>
    {% else %}
    <h1 class="text-center" style="margin-top: 20px;">Sorry!! NO Such page exist</h1>
    {% endif %}
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}